import "./globals.css";
import Script from "next/script";
import Navbar from "@/components/NavBar/NavBar.js";
// import ModalWrapper from "@/components/NewsLetterModal/ModalWrapper";
import ScrollTopButton from "@/components/ScrollTopButton";
import GoogleAnalytics from "@/components/GoogleAnalytics";
import CookieConsent from "@/components/CookieConsent/CookieConsent";

export const metadata = {
  title: "TEDxNTUA-Archive",
  description: "Generated by TEDxNTUA2024-IT",
  icons: [
    {
      rel: "icon",
      type: "image/png",
      sizes: "32x32",
      url: "./favicons/favicon-32x32.png"
    },
    {
      rel: "icon",
      type: "image/png",
      sizes: "16x16",
      url: "./favicons/favicon-16x16.png"
    }
  ]
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <head>
        {/* Google tag (gtag.js) - Added to every page */}
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-E46SH2LTF1"
          strategy="afterInteractive"
        />
        <Script id="gtag-script" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-E46SH2LTF1');
          `}
        </Script>

        {/* Google Analytics - Consent management */}
        <GoogleAnalytics />
      </head>
      <body className="bg-black font-[Helvetica]">
        {/* Cookie Consent Banner */}
        <CookieConsent />
        
        {/* <ModalWrapper />  */}
        <div>
          <ScrollTopButton />
        </div>
        <Navbar />
        <div className="mt-[65px]"></div>
        {children}
      </body>
    </html>
  );
}
