import "./globals.css";

import Navbar from "@/components/NavBar/NavBar.js";
import Footer from "@/components/Footer/Footer";
import NewsLetter from "@/components/NewsLetter/NewsLetter";

export const metadata = {
  title: "TEDxNTUA",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black font-[Helvetica]">
        <Navbar />
        <div className="mt-[5rem]"></div>
        {children}
        <NewsLetter />
        <Footer />
      </body>
    </html>
  );
}
